import type {
  ControlCategory,
  ControlDefinition,
  ControlEvalContext,
  ControlPriority,
} from "@/types/aegis";

type Seed = {
  id: string;
  title: string;
  category: ControlCategory;
  description: string;
  objective: string;
  steps: string[];
  suggested_tools: string[];
  evidence: string[];
  applicability_rules: string[];
  priority_rule: string;
  isApplicable: (context: ControlEvalContext) => boolean;
  getPriority: (context: ControlEvalContext) => ControlPriority;
};

function define(seed: Seed): ControlDefinition {
  return {
    id: seed.id,
    title: seed.title,
    category: seed.category,
    description: seed.description,
    applicability_rules: seed.applicability_rules,
    priority_rule: seed.priority_rule,
    isApplicable: seed.isApplicable,
    getPriority: seed.getPriority,
    how_to_template: {
      objective: seed.objective,
      steps: seed.steps,
      suggested_tools: seed.suggested_tools,
      evidence: seed.evidence,
    },
  };
}

const highIfHighRisk = (ctx: ControlEvalContext): ControlPriority =>
  ctx.risk.level === "High" ? "High" : "Recommended";
const highIfGap = (hasGap: boolean): ControlPriority => (hasGap ? "High" : "Recommended");
const optionalByDefault = (): ControlPriority => "Optional";

const always = () => true;
const ifExternalOrBoth = (ctx: ControlEvalContext) =>
  ctx.profile.deployment === "external" || ctx.profile.deployment === "both";
const ifLLM = (ctx: ControlEvalContext) =>
  ctx.profile.model_type === "LLM" || ctx.profile.model_type === "LLM_RAG";
const ifHighOrMedium = (ctx: ControlEvalContext) =>
  ctx.risk.level === "High" || ctx.risk.level === "Medium";
const ifCustomerFacing = (ctx: ControlEvalContext) => ctx.profile.customer_facing;
const ifPersonalData = (ctx: ControlEvalContext) => ctx.profile.uses_personal_data;

export const controlsKnowledgeBase: ControlDefinition[] = [
  define({
    id: "gov_001",
    title: "AI governance owner assignment",
    category: "Governance/Accountability",
    description: "Assign a named governance owner accountable for controls lifecycle.",
    objective: "Establish clear accountability for AI governance execution.",
    steps: ["Name an accountable owner", "Define scope of decisions", "Review ownership quarterly"],
    suggested_tools: ["RACI matrix", "Work management board"],
    evidence: ["Owner registry", "Quarterly governance review notes"],
    applicability_rules: ["all_systems"],
    priority_rule: "High when risk=High else Recommended",
    isApplicable: always,
    getPriority: highIfHighRisk,
  }),
  define({
    id: "gov_002",
    title: "Policy and standard baseline",
    category: "Governance/Accountability",
    description: "Define baseline policy for model development, release, and monitoring.",
    objective: "Ensure consistent governance expectations across teams.",
    steps: ["Publish baseline policy", "Map policy to lifecycle checkpoints", "Socialize with teams"],
    suggested_tools: ["Policy wiki", "Approval workflow"],
    evidence: ["Policy doc", "Acknowledgement records"],
    applicability_rules: ["all_systems"],
    priority_rule: "Recommended",
    isApplicable: always,
    getPriority: () => "Recommended",
  }),
  define({
    id: "gov_003",
    title: "Risk committee escalation path",
    category: "Governance/Accountability",
    description: "Define escalation for incidents and high-risk model decisions.",
    objective: "Route critical risks to the right decision body quickly.",
    steps: ["Define severity criteria", "Create escalation contacts", "Run tabletop exercises"],
    suggested_tools: ["PagerDuty", "Incident runbooks"],
    evidence: ["Escalation matrix", "Tabletop outcomes"],
    applicability_rules: ["risk>=Medium"],
    priority_rule: "High for High risk else Recommended",
    isApplicable: ifHighOrMedium,
    getPriority: highIfHighRisk,
  }),
  define({
    id: "gov_004",
    title: "Third-party model due diligence",
    category: "Governance/Accountability",
    description: "Review third-party model vendors for controls, privacy, and terms.",
    objective: "Manage dependency risk for external providers.",
    steps: ["Collect vendor security docs", "Review data handling", "Track contractual commitments"],
    suggested_tools: ["Vendor assessment template", "Security questionnaire"],
    evidence: ["Vendor due diligence packet", "Risk acceptance notes"],
    applicability_rules: ["deployment in external,both"],
    priority_rule: "High when risk=High else Recommended",
    isApplicable: ifExternalOrBoth,
    getPriority: highIfHighRisk,
  }),
  define({
    id: "gov_005",
    title: "Data retention and deletion policy",
    category: "Governance/Accountability",
    description: "Set retention timelines and deletion controls for model-related data.",
    objective: "Reduce unnecessary data exposure and liability.",
    steps: ["Define retention classes", "Automate deletion jobs", "Audit deletion logs"],
    suggested_tools: ["Data catalog", "Lifecycle policies"],
    evidence: ["Retention schedule", "Deletion job logs"],
    applicability_rules: ["uses_personal_data=true"],
    priority_rule: "High when personal data + high risk else Recommended",
    isApplicable: ifPersonalData,
    getPriority: (ctx) => (ctx.profile.uses_personal_data && ctx.risk.level === "High" ? "High" : "Recommended"),
  }),
  define({
    id: "gov_006",
    title: "Regulatory inventory mapping",
    category: "Governance/Accountability",
    description: "Maintain inventory of applicable obligations by domain and deployment.",
    objective: "Avoid missing key compliance expectations during rollout.",
    steps: ["Tag systems by domain", "Map obligations by jurisdiction", "Review semiannually"],
    suggested_tools: ["Compliance registry", "Legal tracker"],
    evidence: ["Obligation matrix", "Review meeting notes"],
    applicability_rules: ["all_systems"],
    priority_rule: "Recommended",
    isApplicable: always,
    getPriority: () => "Recommended",
  }),
  define({
    id: "gov_007",
    title: "Change approval gate",
    category: "Governance/Accountability",
    description: "Require governance sign-off before major model or policy changes.",
    objective: "Prevent uncontrolled drift in risk posture.",
    steps: ["Define change thresholds", "Add approval gate in CI/CD", "Log approvals"],
    suggested_tools: ["GitHub checks", "Change management workflow"],
    evidence: ["Approved change records", "Gate configuration"],
    applicability_rules: ["all_systems"],
    priority_rule: "High for fully automated systems",
    isApplicable: always,
    getPriority: (ctx) => (ctx.profile.decision_automation === "FullyAutomated" ? "High" : "Recommended"),
  }),
  define({
    id: "gov_008",
    title: "Risk acceptance register",
    category: "Governance/Accountability",
    description: "Track accepted residual risks with owner and expiry date.",
    objective: "Make risk decisions explicit and time-bound.",
    steps: ["Record residual risk", "Assign owner and expiry", "Review monthly"],
    suggested_tools: ["Risk register", "Ticketing"],
    evidence: ["Risk acceptance records", "Monthly review output"],
    applicability_rules: ["all_systems"],
    priority_rule: "Recommended",
    isApplicable: always,
    getPriority: () => "Recommended",
  }),

  define({
    id: "life_001",
    title: "Requirements traceability",
    category: "Lifecycle",
    description: "Map business requirements to model and control requirements.",
    objective: "Preserve intent across design, implementation, and release.",
    steps: ["Document requirements", "Link to tests and controls", "Review before release"],
    suggested_tools: ["Requirements tracker", "Traceability matrix"],
    evidence: ["Traceability matrix", "Release review checklist"],
    applicability_rules: ["all_systems"],
    priority_rule: "Recommended",
    isApplicable: always,
    getPriority: () => "Recommended",
  }),
  define({
    id: "life_002",
    title: "Dataset versioning",
    category: "Lifecycle",
    description: "Version datasets and feature pipelines used for training and evaluation.",
    objective: "Enable reproducibility and rollback.",
    steps: ["Assign immutable dataset versions", "Track transformations", "Retain metadata"],
    suggested_tools: ["DVC", "Lakehouse metadata"],
    evidence: ["Dataset version tags", "Pipeline manifests"],
    applicability_rules: ["all_systems"],
    priority_rule: "High for High risk",
    isApplicable: always,
    getPriority: highIfHighRisk,
  }),
  define({
    id: "life_003",
    title: "Model release checklist",
    category: "Lifecycle",
    description: "Enforce a release checklist including validation and rollback plan.",
    objective: "Standardize safe model promotion.",
    steps: ["Run pre-release checklist", "Confirm rollback path", "Capture approvals"],
    suggested_tools: ["CI/CD pipeline", "Release runbook"],
    evidence: ["Completed checklist", "Rollback drill record"],
    applicability_rules: ["all_systems"],
    priority_rule: "Recommended",
    isApplicable: always,
    getPriority: () => "Recommended",
  }),
  define({
    id: "life_004",
    title: "Data quality gating",
    category: "Lifecycle",
    description: "Block training/inference on failed data quality checks.",
    objective: "Prevent avoidable quality degradation.",
    steps: ["Define data quality thresholds", "Automate quality checks", "Alert on failures"],
    suggested_tools: ["Great Expectations", "Data observability"],
    evidence: ["Quality threshold config", "Failure alerts"],
    applicability_rules: ["all_systems"],
    priority_rule: "High when impact=High else Recommended",
    isApplicable: always,
    getPriority: (ctx) => (ctx.profile.impact_level === "High" ? "High" : "Recommended"),
  }),
  define({
    id: "life_005",
    title: "Environment parity controls",
    category: "Lifecycle",
    description: "Keep staging and production environments aligned for model behavior.",
    objective: "Reduce environment-induced surprises.",
    steps: ["Mirror critical configs", "Automate config drift checks", "Review monthly"],
    suggested_tools: ["IaC drift detection", "Config scanner"],
    evidence: ["Drift reports", "Config parity checklist"],
    applicability_rules: ["all_systems"],
    priority_rule: "Recommended",
    isApplicable: always,
    getPriority: () => "Recommended",
  }),
  define({
    id: "life_006",
    title: "Prompt/version management",
    category: "Lifecycle",
    description: "Version prompts, retrieval settings, and system instructions.",
    objective: "Track behavior changes in LLM systems.",
    steps: ["Version prompt assets", "Review deltas", "Tag release prompts"],
    suggested_tools: ["Prompt registry", "Git tags"],
    evidence: ["Prompt changelog", "Release tag references"],
    applicability_rules: ["model_type in LLM,LLM_RAG"],
    priority_rule: "High for LLM systems",
    isApplicable: ifLLM,
    getPriority: () => "High",
  }),
  define({
    id: "life_007",
    title: "Rollback and kill switch",
    category: "Lifecycle",
    description: "Support rapid rollback or shutdown for harmful behavior.",
    objective: "Limit blast radius during incidents.",
    steps: ["Implement kill switch", "Document rollback process", "Drill quarterly"],
    suggested_tools: ["Feature flags", "Runtime policy engine"],
    evidence: ["Kill switch test logs", "Rollback drill output"],
    applicability_rules: ["risk>=Medium"],
    priority_rule: "High for High risk else Recommended",
    isApplicable: ifHighOrMedium,
    getPriority: highIfHighRisk,
  }),
  define({
    id: "life_008",
    title: "Post-incident corrective action loop",
    category: "Lifecycle",
    description: "Feed incident learnings back into design and release controls.",
    objective: "Continuously improve resilience.",
    steps: ["Run postmortem", "Create corrective actions", "Track completion"],
    suggested_tools: ["Incident tracker", "Action log"],
    evidence: ["Postmortems", "Completed action tickets"],
    applicability_rules: ["all_systems"],
    priority_rule: "Recommended",
    isApplicable: always,
    getPriority: () => "Recommended",
  }),

  define({
    id: "rob_001",
    title: "Adversarial robustness tests",
    category: "Robustness",
    description: "Run perturbation and adversarial input tests before release.",
    objective: "Validate model stability under challenging conditions.",
    steps: ["Define adversarial scenarios", "Run robustness test suite", "Track fail/pass trend"],
    suggested_tools: ["Robustness benchmark suite", "Evaluation pipelines"],
    evidence: ["Robustness test results", "Issue remediation log"],
    applicability_rules: ["robustness.required=true"],
    priority_rule: "High if robustness gap exists else Recommended",
    isApplicable: (ctx) => ctx.gaps.robustness.required,
    getPriority: (ctx) => highIfGap(ctx.gaps.robustness.gaps.length > 0),
  }),
  define({
    id: "rob_002",
    title: "Out-of-distribution detection",
    category: "Robustness",
    description: "Detect and handle OOD inputs at inference time.",
    objective: "Reduce unreliable predictions on unfamiliar data.",
    steps: ["Set OOD thresholds", "Add fallback response", "Log OOD events"],
    suggested_tools: ["Embedding distance monitor", "Confidence calibration"],
    evidence: ["OOD threshold docs", "OOD incident trends"],
    applicability_rules: ["model_type in LLM,LLM_RAG or impact=High"],
    priority_rule: "Recommended",
    isApplicable: (ctx) => ctx.gaps.robustness.required,
    getPriority: () => "Recommended",
  }),
  define({
    id: "rob_003",
    title: "Latency and throughput stress tests",
    category: "Robustness",
    description: "Test system under realistic and peak load.",
    objective: "Ensure service reliability under demand spikes.",
    steps: ["Define SLOs", "Run stress tests", "Tune autoscaling and budgets"],
    suggested_tools: ["k6", "Locust"],
    evidence: ["Load test reports", "SLO dashboard snapshots"],
    applicability_rules: ["customer_facing=true"],
    priority_rule: "High for customer-facing high-risk systems",
    isApplicable: ifCustomerFacing,
    getPriority: (ctx) => (ctx.profile.customer_facing && ctx.risk.level === "High" ? "High" : "Recommended"),
  }),
  define({
    id: "rob_004",
    title: "Fallback and graceful degradation",
    category: "Robustness",
    description: "Define fallback behavior when model confidence is low.",
    objective: "Avoid hard failures and preserve service continuity.",
    steps: ["Define fallback path", "Implement confidence threshold", "Test fallback behavior"],
    suggested_tools: ["Feature flags", "Rule-based fallback service"],
    evidence: ["Fallback policy", "Fallback simulation logs"],
    applicability_rules: ["all_systems"],
    priority_rule: "Recommended",
    isApplicable: always,
    getPriority: () => "Recommended",
  }),
  define({
    id: "rob_005",
    title: "Inference error budget policy",
    category: "Robustness",
    description: "Set error budget and release constraints for model quality regressions.",
    objective: "Prevent quality regression from accumulating silently.",
    steps: ["Define error budget", "Block release on breach", "Review monthly"],
    suggested_tools: ["Quality dashboard", "CI gate"],
    evidence: ["Error budget policy", "Blocked release records"],
    applicability_rules: ["risk>=Medium"],
    priority_rule: "Recommended",
    isApplicable: ifHighOrMedium,
    getPriority: () => "Recommended",
  }),
  define({
    id: "rob_006",
    title: "Retrieval integrity checks",
    category: "Robustness",
    description: "Validate retrieval freshness and relevance for RAG systems.",
    objective: "Reduce hallucination from stale/irrelevant context.",
    steps: ["Track retrieval precision", "Set staleness thresholds", "Automate re-indexing cadence"],
    suggested_tools: ["Vector DB metrics", "Offline eval suite"],
    evidence: ["Retrieval metrics report", "Re-index job logs"],
    applicability_rules: ["model_type=LLM_RAG"],
    priority_rule: "High for LLM_RAG",
    isApplicable: (ctx) => ctx.profile.model_type === "LLM_RAG",
    getPriority: () => "High",
  }),
  define({
    id: "rob_007",
    title: "Chaos testing for dependencies",
    category: "Robustness",
    description: "Inject dependency failures to validate resilience.",
    objective: "Prepare system for degraded upstream services.",
    steps: ["Inject API failures", "Observe fallback behavior", "Patch weak points"],
    suggested_tools: ["Chaos engineering tools", "Fault injection proxy"],
    evidence: ["Chaos run report", "Resilience fixes"],
    applicability_rules: ["deployment external or both"],
    priority_rule: "Recommended",
    isApplicable: ifExternalOrBoth,
    getPriority: () => "Recommended",
  }),
  define({
    id: "rob_008",
    title: "Prompt robustness benchmark",
    category: "Robustness",
    description: "Evaluate prompt sensitivity across phrasing variants.",
    objective: "Ensure stable outcomes for semantically equivalent requests.",
    steps: ["Create paraphrase sets", "Measure response variance", "Refine prompts"],
    suggested_tools: ["Prompt testing harness", "Statistical variance report"],
    evidence: ["Prompt robustness benchmark", "Prompt revision history"],
    applicability_rules: ["model_type in LLM,LLM_RAG"],
    priority_rule: "Recommended",
    isApplicable: ifLLM,
    getPriority: () => "Recommended",
  }),

  define({
    id: "fair_001",
    title: "Fairness metric definition",
    category: "Fairness",
    description: "Define fairness metrics aligned with use-case and domain context.",
    objective: "Set explicit fairness expectations before deployment.",
    steps: ["Select fairness metrics", "Set thresholds", "Document rationale"],
    suggested_tools: ["Fairlearn", "Metric dashboard"],
    evidence: ["Fairness metric spec", "Threshold review notes"],
    applicability_rules: ["fairness.required=true"],
    priority_rule: "High if fairness gap exists else Recommended",
    isApplicable: (ctx) => ctx.gaps.fairness.required,
    getPriority: (ctx) => highIfGap(ctx.gaps.fairness.gaps.length > 0),
  }),
  define({
    id: "fair_002",
    title: "Sensitive attribute handling policy",
    category: "Fairness",
    description: "Define approved use and protections around sensitive attributes.",
    objective: "Reduce unintended discriminatory outcomes.",
    steps: ["Catalog sensitive signals", "Define allowable usage", "Add review checkpoints"],
    suggested_tools: ["Data inventory", "Policy checks"],
    evidence: ["Sensitive attribute policy", "Approval records"],
    applicability_rules: ["uses_personal_data=true"],
    priority_rule: "Recommended",
    isApplicable: ifPersonalData,
    getPriority: () => "Recommended",
  }),
  define({
    id: "fair_003",
    title: "Bias test dataset curation",
    category: "Fairness",
    description: "Maintain representative and challenging fairness evaluation datasets.",
    objective: "Measure fairness with realistic and stress scenarios.",
    steps: ["Curate benchmark slices", "Refresh datasets", "Track coverage"],
    suggested_tools: ["Dataset registry", "Bias benchmark suite"],
    evidence: ["Dataset curation log", "Coverage report"],
    applicability_rules: ["fairness.required=true"],
    priority_rule: "Recommended",
    isApplicable: (ctx) => ctx.gaps.fairness.required,
    getPriority: () => "Recommended",
  }),
  define({
    id: "fair_004",
    title: "Counterfactual fairness checks",
    category: "Fairness",
    description: "Run counterfactual tests to evaluate sensitivity to protected traits.",
    objective: "Identify causal unfairness patterns.",
    steps: ["Design counterfactual pairs", "Run parity analysis", "Log corrective changes"],
    suggested_tools: ["Counterfactual testing tool", "Model audit notebooks"],
    evidence: ["Counterfactual test report", "Mitigation change log"],
    applicability_rules: ["domain in lending,hiring,pricing,fraud"],
    priority_rule: "High",
    isApplicable: (ctx) => ["lending", "hiring", "pricing", "fraud"].includes(ctx.profile.domain),
    getPriority: () => "High",
  }),
  define({
    id: "fair_005",
    title: "Fairness sign-off gate",
    category: "Fairness",
    description: "Require fairness review approval for model release.",
    objective: "Block launch when fairness criteria are unmet.",
    steps: ["Attach fairness report to release", "Require sign-off", "Store approval history"],
    suggested_tools: ["Release checks", "Approval workflow"],
    evidence: ["Fairness sign-off records", "Release gate logs"],
    applicability_rules: ["fairness.required=true"],
    priority_rule: "High for High risk",
    isApplicable: (ctx) => ctx.gaps.fairness.required,
    getPriority: highIfHighRisk,
  }),
  define({
    id: "fair_006",
    title: "User harm feedback channel",
    category: "Fairness",
    description: "Capture and triage user complaints related to harmful or biased outputs.",
    objective: "Use real-world feedback to improve fairness outcomes.",
    steps: ["Add feedback channel", "Define triage SLAs", "Track remediation"],
    suggested_tools: ["Support queue", "Issue tracker"],
    evidence: ["Complaint taxonomy", "Remediation records"],
    applicability_rules: ["customer_facing=true"],
    priority_rule: "Recommended",
    isApplicable: ifCustomerFacing,
    getPriority: () => "Recommended",
  }),
  define({
    id: "fair_007",
    title: "Fairness drift monitoring",
    category: "Fairness",
    description: "Monitor fairness metrics over time after deployment.",
    objective: "Detect fairness degradation caused by data or behavior drift.",
    steps: ["Define drift thresholds", "Schedule recurring evaluations", "Escalate threshold breaches"],
    suggested_tools: ["Monitoring dashboards", "Scheduled evaluation jobs"],
    evidence: ["Fairness trend chart", "Alert history"],
    applicability_rules: ["fairness.required=true"],
    priority_rule: "Recommended",
    isApplicable: (ctx) => ctx.gaps.fairness.required,
    getPriority: () => "Recommended",
  }),
  define({
    id: "fair_008",
    title: "Targeted mitigation playbook",
    category: "Fairness",
    description: "Maintain predefined mitigation options for fairness issues.",
    objective: "Accelerate response when fairness gaps are identified.",
    steps: ["List mitigation tactics", "Map to trigger conditions", "Practice execution drills"],
    suggested_tools: ["Runbooks", "Experiment platform"],
    evidence: ["Mitigation playbook", "Drill records"],
    applicability_rules: ["fairness.required=true"],
    priority_rule: "High if fairness gap exists else Recommended",
    isApplicable: (ctx) => ctx.gaps.fairness.required,
    getPriority: (ctx) => highIfGap(ctx.gaps.fairness.gaps.length > 0),
  }),

  define({
    id: "safe_001",
    title: "Prompt injection defense",
    category: "Safety",
    description: "Deploy layered controls to detect and neutralize prompt injection attempts.",
    objective: "Reduce manipulation risk in instruction-following systems.",
    steps: ["Add prompt sanitization", "Isolate system prompt context", "Test known injection patterns"],
    suggested_tools: ["Prompt firewall", "Safety classifier"],
    evidence: ["Prompt injection test results", "Blocked injection logs"],
    applicability_rules: ["model_type in LLM,LLM_RAG"],
    priority_rule: "High",
    isApplicable: ifLLM,
    getPriority: () => "High",
  }),
  define({
    id: "safe_002",
    title: "Data leakage prevention",
    category: "Safety",
    description: "Prevent model outputs from leaking sensitive or proprietary information.",
    objective: "Protect confidential and personal data from unintended disclosure.",
    steps: ["Apply output redaction policy", "Scan outputs for sensitive patterns", "Block risky responses"],
    suggested_tools: ["DLP scanner", "PII detector"],
    evidence: ["Leakage scan reports", "Blocked output logs"],
    applicability_rules: ["uses_personal_data=true OR deployment external/both"],
    priority_rule: "High when personal data is used",
    isApplicable: (ctx) => ifPersonalData(ctx) || ifExternalOrBoth(ctx),
    getPriority: (ctx) => (ctx.profile.uses_personal_data ? "High" : "Recommended"),
  }),
  define({
    id: "safe_003",
    title: "Unsafe content policy enforcement",
    category: "Safety",
    description: "Enforce safety policy for harmful content generation or recommendations.",
    objective: "Prevent unsafe outputs from reaching end users.",
    steps: ["Define prohibited categories", "Add moderation checks", "Tune refusal behavior"],
    suggested_tools: ["Content moderation API", "Policy engine"],
    evidence: ["Policy config", "Moderation metrics"],
    applicability_rules: ["customer_facing=true OR model_type in LLM,LLM_RAG"],
    priority_rule: "High for customer-facing high-risk systems",
    isApplicable: (ctx) => ifCustomerFacing(ctx) || ifLLM(ctx),
    getPriority: (ctx) => (ctx.profile.customer_facing && ctx.risk.level === "High" ? "High" : "Recommended"),
  }),
  define({
    id: "safe_004",
    title: "Tool invocation sandboxing",
    category: "Safety",
    description: "Restrict and audit model-initiated tool actions.",
    objective: "Limit harmful side effects from autonomous actions.",
    steps: ["Define allowlist", "Require explicit approvals for high-risk actions", "Log tool calls"],
    suggested_tools: ["Policy gateway", "Audit logger"],
    evidence: ["Tool allowlist", "Tool invocation audit trail"],
    applicability_rules: ["decision_automation=FullyAutomated OR model_type in LLM,LLM_RAG"],
    priority_rule: "High",
    isApplicable: (ctx) => ctx.profile.decision_automation === "FullyAutomated" || ifLLM(ctx),
    getPriority: () => "High",
  }),
  define({
    id: "safe_005",
    title: "Jailbreak regression suite",
    category: "Safety",
    description: "Run recurring jailbreak tests and compare against baseline.",
    objective: "Track and improve resistance against known attack prompts.",
    steps: ["Maintain jailbreak corpus", "Run scheduled tests", "Patch failures rapidly"],
    suggested_tools: ["Red-team test harness", "CI jobs"],
    evidence: ["Jailbreak benchmark trends", "Issue closure records"],
    applicability_rules: ["model_type in LLM,LLM_RAG"],
    priority_rule: "Recommended",
    isApplicable: ifLLM,
    getPriority: () => "Recommended",
  }),
  define({
    id: "safe_006",
    title: "Abuse monitoring and response",
    category: "Safety",
    description: "Detect misuse patterns and trigger rapid response workflows.",
    objective: "Contain abuse behavior and reduce downstream harm.",
    steps: ["Define abuse indicators", "Set alerts", "Run response playbook"],
    suggested_tools: ["Security monitoring", "SIEM"],
    evidence: ["Abuse alert history", "Response timeline report"],
    applicability_rules: ["customer_facing=true"],
    priority_rule: "Recommended",
    isApplicable: ifCustomerFacing,
    getPriority: () => "Recommended",
  }),
  define({
    id: "safe_007",
    title: "External API egress controls",
    category: "Safety",
    description: "Control data egress and enforce destination restrictions.",
    objective: "Limit uncontrolled external transmission.",
    steps: ["Define approved endpoints", "Apply egress filter", "Log denied egress attempts"],
    suggested_tools: ["Network policy", "Proxy rules"],
    evidence: ["Egress policy", "Denied request logs"],
    applicability_rules: ["deployment external/both"],
    priority_rule: "High when risk=High",
    isApplicable: ifExternalOrBoth,
    getPriority: highIfHighRisk,
  }),
  define({
    id: "safe_008",
    title: "Safety incident runbook",
    category: "Safety",
    description: "Create runbook for safety failures and harmful output incidents.",
    objective: "Respond consistently and quickly to safety events.",
    steps: ["Define severity levels", "Assign response owners", "Exercise runbook quarterly"],
    suggested_tools: ["Incident runbook", "Pager system"],
    evidence: ["Safety runbook", "Exercise report"],
    applicability_rules: ["safety.required=true"],
    priority_rule: "High if safety gap exists else Recommended",
    isApplicable: (ctx) => ctx.gaps.safety.required,
    getPriority: (ctx) => highIfGap(ctx.gaps.safety.gaps.length > 0),
  }),

  define({
    id: "exp_001",
    title: "Model card publication",
    category: "Explainability",
    description: "Publish model card with intended use, limits, and evaluation summary.",
    objective: "Provide a standard transparency artifact for stakeholders.",
    steps: ["Draft model card", "Review with stakeholders", "Publish and version"],
    suggested_tools: ["Model card template", "Documentation portal"],
    evidence: ["Published model card", "Version changelog"],
    applicability_rules: ["explainability.required=true"],
    priority_rule: "High if explainability gap exists else Recommended",
    isApplicable: (ctx) => ctx.gaps.explainability.required,
    getPriority: (ctx) => highIfGap(ctx.gaps.explainability.gaps.length > 0),
  }),
  define({
    id: "exp_002",
    title: "Global explanation package",
    category: "Explainability",
    description: "Document global behavior patterns and key drivers.",
    objective: "Help governance teams understand broad model behavior.",
    steps: ["Generate global explanation", "Review with SMEs", "Store with release artifacts"],
    suggested_tools: ["SHAP summary", "Feature importance report"],
    evidence: ["Global explanation report", "SME review notes"],
    applicability_rules: ["all_systems"],
    priority_rule: "Recommended",
    isApplicable: always,
    getPriority: () => "Recommended",
  }),
  define({
    id: "exp_003",
    title: "Local explanation support",
    category: "Explainability",
    description: "Provide per-instance explanation for high-impact decisions.",
    objective: "Enable case-level review and user recourse.",
    steps: ["Implement local explanation endpoint", "Show explanation in review UI", "Log explanation metadata"],
    suggested_tools: ["LIME", "SHAP local"],
    evidence: ["Local explanation samples", "Reviewer sign-off"],
    applicability_rules: ["impact_level=High OR domain in lending,hiring,pricing,fraud"],
    priority_rule: "High",
    isApplicable: (ctx) =>
      ctx.profile.impact_level === "High" ||
      ["lending", "hiring", "pricing", "fraud"].includes(ctx.profile.domain),
    getPriority: () => "High",
  }),
  define({
    id: "exp_004",
    title: "User-facing AI disclosure",
    category: "Explainability",
    description: "Disclose AI involvement and expected limitations to end users.",
    objective: "Improve transparency and informed use.",
    steps: ["Draft disclosure copy", "Place near interaction points", "Review comprehension"],
    suggested_tools: ["UX copy guidelines", "A/B test"],
    evidence: ["Disclosure screenshots", "Comprehension test results"],
    applicability_rules: ["customer_facing=true"],
    priority_rule: "Recommended",
    isApplicable: ifCustomerFacing,
    getPriority: () => "Recommended",
  }),
  define({
    id: "exp_005",
    title: "Decision reason code taxonomy",
    category: "Explainability",
    description: "Standardize reason codes for decision outcomes.",
    objective: "Enable consistent communication and auditability.",
    steps: ["Define reason code catalog", "Map model outputs", "Validate with reviewers"],
    suggested_tools: ["Reason code dictionary", "Audit workflow"],
    evidence: ["Reason code catalog", "Mapping validation results"],
    applicability_rules: ["decision_automation in Partial,FullyAutomated"],
    priority_rule: "Recommended",
    isApplicable: (ctx) => ctx.profile.decision_automation !== "HumanReview",
    getPriority: () => "Recommended",
  }),
  define({
    id: "exp_006",
    title: "Prompt and context transparency note",
    category: "Explainability",
    description: "Document how prompts/context influence model outputs.",
    objective: "Clarify behavioral dependencies in LLM pipelines.",
    steps: ["Describe prompt design intent", "List context sources", "Document failure modes"],
    suggested_tools: ["Prompt documentation template", "Knowledge source map"],
    evidence: ["Prompt/context note", "Failure mode matrix"],
    applicability_rules: ["model_type in LLM,LLM_RAG"],
    priority_rule: "Recommended",
    isApplicable: ifLLM,
    getPriority: () => "Recommended",
  }),
  define({
    id: "exp_007",
    title: "Explainability QA review",
    category: "Explainability",
    description: "Validate explanation quality for accuracy and readability.",
    objective: "Ensure explanations are useful and not misleading.",
    steps: ["Sample explanations", "Score readability and fidelity", "Fix weak areas"],
    suggested_tools: ["Human review rubric", "QA checklist"],
    evidence: ["Explainability QA scores", "Improvement tickets"],
    applicability_rules: ["all_systems"],
    priority_rule: "Optional",
    isApplicable: always,
    getPriority: optionalByDefault,
  }),
  define({
    id: "exp_008",
    title: "Explanation retention policy",
    category: "Explainability",
    description: "Retain explanation artifacts for audit and dispute handling.",
    objective: "Support traceability over decision lifecycle.",
    steps: ["Define retention window", "Store explanation payload securely", "Audit retention quarterly"],
    suggested_tools: ["Secure archive", "Retention jobs"],
    evidence: ["Retention policy", "Archive audit report"],
    applicability_rules: ["decision_automation != HumanReview"],
    priority_rule: "Recommended",
    isApplicable: (ctx) => ctx.profile.decision_automation !== "HumanReview",
    getPriority: () => "Recommended",
  }),

  define({
    id: "mon_001",
    title: "Production quality monitoring",
    category: "Monitoring",
    description: "Track quality metrics and detect degradation in production.",
    objective: "Identify model performance issues quickly.",
    steps: ["Define production KPIs", "Set alert thresholds", "Escalate breaches"],
    suggested_tools: ["Monitoring dashboards", "Alert manager"],
    evidence: ["KPI dashboards", "Alert incident records"],
    applicability_rules: ["all_systems"],
    priority_rule: "High for High risk else Recommended",
    isApplicable: always,
    getPriority: highIfHighRisk,
  }),
  define({
    id: "mon_002",
    title: "Data drift monitoring",
    category: "Monitoring",
    description: "Monitor shifts in inference data distributions.",
    objective: "Detect data drift before it causes major regressions.",
    steps: ["Baseline production distributions", "Run drift detectors", "Trigger retraining/review"],
    suggested_tools: ["Evidently", "Data quality monitors"],
    evidence: ["Drift reports", "Triggered mitigation actions"],
    applicability_rules: ["all_systems"],
    priority_rule: "Recommended",
    isApplicable: always,
    getPriority: () => "Recommended",
  }),
  define({
    id: "mon_003",
    title: "Latency and availability SLOs",
    category: "Monitoring",
    description: "Track operational reliability against explicit SLOs.",
    objective: "Maintain acceptable service quality for users.",
    steps: ["Define SLO targets", "Instrument endpoints", "Review SLO misses weekly"],
    suggested_tools: ["APM", "SLO dashboard"],
    evidence: ["SLO definitions", "Weekly reliability review"],
    applicability_rules: ["customer_facing=true"],
    priority_rule: "Recommended",
    isApplicable: ifCustomerFacing,
    getPriority: () => "Recommended",
  }),
  define({
    id: "mon_004",
    title: "Safety event telemetry",
    category: "Monitoring",
    description: "Track safety-related failures and policy violations.",
    objective: "Measure and reduce harmful interactions over time.",
    steps: ["Define safety event taxonomy", "Instrument safety logging", "Trend analysis monthly"],
    suggested_tools: ["SIEM", "Safety analytics dashboard"],
    evidence: ["Safety telemetry dashboard", "Monthly trend report"],
    applicability_rules: ["safety.required=true"],
    priority_rule: "High if safety gap exists else Recommended",
    isApplicable: (ctx) => ctx.gaps.safety.required,
    getPriority: (ctx) => highIfGap(ctx.gaps.safety.gaps.length > 0),
  }),
  define({
    id: "mon_005",
    title: "Feedback loop instrumentation",
    category: "Monitoring",
    description: "Capture user and reviewer feedback tied to output IDs.",
    objective: "Create actionable loop from production to improvements.",
    steps: ["Add feedback capture UI", "Link to output trace IDs", "Review trends weekly"],
    suggested_tools: ["Feedback API", "Analytics warehouse"],
    evidence: ["Feedback trend report", "Action backlog"],
    applicability_rules: ["customer_facing=true"],
    priority_rule: "Recommended",
    isApplicable: ifCustomerFacing,
    getPriority: () => "Recommended",
  }),
  define({
    id: "mon_006",
    title: "Model version observability",
    category: "Monitoring",
    description: "Tag logs/metrics with model and prompt versions.",
    objective: "Enable precise incident debugging and rollback decisions.",
    steps: ["Annotate telemetry with versions", "Expose version in dashboards", "Validate after each release"],
    suggested_tools: ["Structured logging", "APM tags"],
    evidence: ["Telemetry schema", "Version-tagged dashboard"],
    applicability_rules: ["all_systems"],
    priority_rule: "Recommended",
    isApplicable: always,
    getPriority: () => "Recommended",
  }),
  define({
    id: "mon_007",
    title: "Cost and token budget monitoring",
    category: "Monitoring",
    description: "Track model usage cost and budget thresholds.",
    objective: "Avoid runaway operating costs and quota failures.",
    steps: ["Define budget thresholds", "Alert on abnormal spikes", "Tune prompts/retrieval"],
    suggested_tools: ["Cloud cost explorer", "Usage analytics"],
    evidence: ["Budget dashboard", "Optimization actions"],
    applicability_rules: ["model_type in LLM,LLM_RAG"],
    priority_rule: "Recommended",
    isApplicable: ifLLM,
    getPriority: () => "Recommended",
  }),
  define({
    id: "mon_008",
    title: "Periodic governance health review",
    category: "Monitoring",
    description: "Review risk, controls, and incidents on a fixed cadence.",
    objective: "Keep governance posture current over time.",
    steps: ["Schedule monthly review", "Assess control status", "Record follow-up actions"],
    suggested_tools: ["Governance dashboard", "Review template"],
    evidence: ["Monthly review log", "Follow-up ticket list"],
    applicability_rules: ["all_systems"],
    priority_rule: "Recommended",
    isApplicable: always,
    getPriority: () => "Recommended",
  }),

  define({
    id: "human_001",
    title: "Human-in-the-loop approval queue",
    category: "Human Oversight",
    description: "Require human approval for high-impact or low-confidence outputs.",
    objective: "Prevent unchecked automated decisions in sensitive contexts.",
    steps: ["Define approval criteria", "Route decisions to queue", "Track reviewer outcomes"],
    suggested_tools: ["Review queue UI", "Workflow engine"],
    evidence: ["Approval queue logs", "Reviewer decision records"],
    applicability_rules: ["decision_automation in Partial,FullyAutomated"],
    priority_rule: "High when risk=High",
    isApplicable: (ctx) => ctx.profile.decision_automation !== "HumanReview",
    getPriority: highIfHighRisk,
  }),
  define({
    id: "human_002",
    title: "Reviewer training standard",
    category: "Human Oversight",
    description: "Train reviewers on domain risks, escalation, and consistency guidelines.",
    objective: "Improve oversight quality and consistency.",
    steps: ["Define training modules", "Certify reviewers", "Refresh training quarterly"],
    suggested_tools: ["LMS", "Reviewer handbook"],
    evidence: ["Training completion records", "Calibration exercise results"],
    applicability_rules: ["human review is used"],
    priority_rule: "Recommended",
    isApplicable: (ctx) => ctx.profile.decision_automation !== "FullyAutomated",
    getPriority: () => "Recommended",
  }),
  define({
    id: "human_003",
    title: "Override and appeal mechanism",
    category: "Human Oversight",
    description: "Allow human override and user appeal for model outcomes.",
    objective: "Provide recourse and correction pathways.",
    steps: ["Implement override controls", "Define appeal SLA", "Track appeal outcomes"],
    suggested_tools: ["Case management", "Ticketing"],
    evidence: ["Override logs", "Appeal resolution metrics"],
    applicability_rules: ["customer_facing=true OR impact_level=High"],
    priority_rule: "High",
    isApplicable: (ctx) => ctx.profile.customer_facing || ctx.profile.impact_level === "High",
    getPriority: () => "High",
  }),
  define({
    id: "human_004",
    title: "Dual-control for sensitive decisions",
    category: "Human Oversight",
    description: "Require two-person approval for designated high-impact cases.",
    objective: "Reduce single-point judgment errors.",
    steps: ["Define dual-control scope", "Implement second reviewer assignment", "Audit compliance"],
    suggested_tools: ["Workflow approvals", "Audit reports"],
    evidence: ["Dual-approval records", "Compliance audit"],
    applicability_rules: ["impact_level=High"],
    priority_rule: "High",
    isApplicable: (ctx) => ctx.profile.impact_level === "High",
    getPriority: () => "High",
  }),
  define({
    id: "human_005",
    title: "Reviewer calibration sessions",
    category: "Human Oversight",
    description: "Run periodic calibration to align reviewer decisions.",
    objective: "Maintain consistent quality in human oversight outcomes.",
    steps: ["Sample ambiguous cases", "Compare reviewer outcomes", "Update guidelines"],
    suggested_tools: ["Calibration rubric", "Review analytics"],
    evidence: ["Calibration scorecards", "Guideline updates"],
    applicability_rules: ["human review used"],
    priority_rule: "Recommended",
    isApplicable: (ctx) => ctx.profile.decision_automation !== "FullyAutomated",
    getPriority: () => "Recommended",
  }),
  define({
    id: "human_006",
    title: "Escalation for uncertain outputs",
    category: "Human Oversight",
    description: "Route uncertain outputs to specialist reviewers.",
    objective: "Improve decision quality for edge and ambiguous cases.",
    steps: ["Define uncertainty thresholds", "Set specialist queues", "Track turnaround and quality"],
    suggested_tools: ["Confidence scoring", "Queue routing"],
    evidence: ["Escalation logs", "Specialist outcome review"],
    applicability_rules: ["all_systems"],
    priority_rule: "Recommended",
    isApplicable: always,
    getPriority: () => "Recommended",
  }),
  define({
    id: "human_007",
    title: "Decision rationale capture",
    category: "Human Oversight",
    description: "Require reviewers to document rationale on overrides and escalations.",
    objective: "Improve transparency and future learning.",
    steps: ["Define rationale schema", "Make rationale mandatory", "Review rationale quality"],
    suggested_tools: ["Structured forms", "Audit review"],
    evidence: ["Reviewer rationale records", "Quality review summaries"],
    applicability_rules: ["human review used"],
    priority_rule: "Recommended",
    isApplicable: (ctx) => ctx.profile.decision_automation !== "FullyAutomated",
    getPriority: () => "Recommended",
  }),
  define({
    id: "human_008",
    title: "Override impact analytics",
    category: "Human Oversight",
    description: "Measure override frequency and root causes over time.",
    objective: "Identify model weaknesses and improve trust calibration.",
    steps: ["Track override rates by segment", "Analyze root causes", "Feed improvements to model lifecycle"],
    suggested_tools: ["Analytics dashboard", "Issue tracker"],
    evidence: ["Override trend dashboard", "Improvement action list"],
    applicability_rules: ["decision_automation in Partial,FullyAutomated"],
    priority_rule: "Optional",
    isApplicable: (ctx) => ctx.profile.decision_automation !== "HumanReview",
    getPriority: optionalByDefault,
  }),
];

