import type { AI_System_Profile } from "@/types/aegis";

export const defaultSystemProfile: AI_System_Profile = {
  system_name: "",
  use_case_summary: "",
  model_type: "LLM",
  customer_facing: true,
  impact_level: "Medium",
  uses_personal_data: true,
  decision_automation: "Partial",
  domain: "customer_support",
  decision_context: "",
  affected_stakeholders: [],
  high_risk_decision: false,
  data_sources: [],
  sensitive_data_types: [],
  data_retention_policy: "",
  cross_border_data_transfer: false,
  third_party_data_sharing: false,
  deployment: "internal",
  model_provider: "",
  model_version: "",
  change_management_process: false,
  has_robustness_testing: false,
  has_fairness_testing: false,
  has_safety_testing: false,
  has_model_card: false,
  prompt_injection_testing: false,
  data_leakage_testing: false,
  tool_call_restrictions: false,
  human_review_trigger: "",
  appeal_mechanism: false,
  incident_response_playbook: false,
  monitoring_metrics: [],
  alert_threshold_defined: false,
  fairness_method: "",
  explanation_mechanism: "",
  compliance_frameworks: [],
  notes: "",
};

export function normalizeProfile(input: AI_System_Profile): AI_System_Profile {
  return {
    ...input,
    system_name: input.system_name.trim(),
    use_case_summary: input.use_case_summary.trim(),
    decision_context: input.decision_context.trim(),
    affected_stakeholders: input.affected_stakeholders.map((item) => item.trim()).filter(Boolean),
    data_sources: input.data_sources.map((item) => item.trim()).filter(Boolean),
    sensitive_data_types: input.sensitive_data_types.map((item) => item.trim()).filter(Boolean),
    data_retention_policy: input.data_retention_policy.trim(),
    model_provider: input.model_provider.trim(),
    model_version: input.model_version.trim(),
    human_review_trigger: input.human_review_trigger.trim(),
    monitoring_metrics: input.monitoring_metrics.map((item) => item.trim()).filter(Boolean),
    fairness_method: input.fairness_method.trim(),
    explanation_mechanism: input.explanation_mechanism.trim(),
    compliance_frameworks: input.compliance_frameworks.map((item) => item.trim()).filter(Boolean),
    notes: input.notes?.trim() || "",
  };
}
